version: '2'
services:
    mysql:
        image: mysql:5.6.40
        container_name: mysql-server
        volumes:
          - .:/application
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tasks
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
            - "8001:3306"
    website:
        container_name: php72
        build:
            context: ./
        volumes:
            - ./:/var/www/html
        ports:
            - 8000:80
